teams/teamc.yaml
... a new team wants a deployment
=> [NEW TEAM] Add a new cluster/team/deployment

.gitignore, README.md, scripts/create_cluster_config.sh, terraform/templates/cluster.tf
We'd like to have a nice way of deploying clusters as and when we need
them.
We believe, Typhoon would be our preferred way of deploying clusters for
people including ourselves. It would give us nice room to improve and
modify as and when required.
This means we need a good way of defining new clusters therefore
providing a script to generate the template.
Documenting the use/approach to be repeatable by humans and perhaps be
adaptable to the CI/CD way.
1. Read through the docs
2. Attempt at spinning up a new cluster
=> Spin up a cluster with Typhoon

.gitignore, terraform/modules/github-flux/data/flux.yaml, terraform/modules/github-flux/main.tf, terraform/modules/github-flux/variables.tf, terraform/templates/cluster.tf
=> Tidying up some flux loose ends.

scripts/initialise_canary_helm_codecommit.sh
Previously, we were only initialising the repository and operated on
empty dir. We're now adding a command to pull down the latest state from
the source master branch.
- Make sure my thinking makes sense
- This can only be possibly tested on initial `terraform apply` of a new cluster
=> Pull source code

terraform/clusters/cluster.re-managed-observe-production.aws.ext.govsvc.uk/cluster.tf, terraform/clusters/cluster.re-managed-observe-staging.aws.ext.govsvc.uk/cluster.tf, terraform/clusters/farms.re-run-sandbox.aws.ext.govsvc.uk/cluster.tf
Adds SealedSecret releases to all clusters
=> Add sealed secrets

terraform/accounts/verify/clusters/tools/cluster.tf
We've got pipelines, let's deploy them to the cluster auto-magically.
- Code review
- Check the pipelines URL
=> Auto-deploy eIDAS Pipelines

terraform/accounts/verify/clusters/prod/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf, terraform/clusters/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/cluster.tf
To fix weird terraform init pipeline bug... since we have
removed our only null resource but it likely still exists
in the state file.
=> Add null provider

terraform/accounts/verify/clusters/prod/cluster.tf, terraform/accounts/verify/clusters/staging/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf, terraform/clusters/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/cluster.tf
No longer needed as part of a two step process to fix our null
provider bug
=> Remove nulls

terraform/clusters/samcrang.run-sandbox.aws.ext.govsvc.uk/cluster.tf
This gets created as part of the gsp-cluster module now.
=> Remove old pipelines module

terraform/accounts/verify/clusters/staging/cluster.tf
=> Fix incorrect path

terraform/accounts/verify/clusters/prod/cluster.tf, terraform/accounts/verify/clusters/staging/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf
A revert of alphagov/gsp-teams#71
- Code review
- See if pipeline has passed after [verify/terraform#75](https://cd.gds-reliability.engineering/teams/gsp/pipelines/verify/jobs/terraform/builds/75)
=> Empty archive provider removal

terraform/accounts/verify/clusters/staging/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf
_ETA: February 1st_
Pen-tests are over. Let's revoke the access we've granted.
- **Make sure the pen-tests are over!**
- Sanity check
=> [ETA: February 1st] Revert "Add Nettitude’s IP for pen-tests"

terraform/modules/hsm/main.tf
* Fixes typo in terraform variable name
* Renames security group rule
=> Fix typo in hsm module variable name

pipelines/tools-staging-prod-infra.yaml
* update pipeline to trigger on changes to things in terraform/modules/hsm
Already deployed
=> trigger gsp-teams on module change

terraform/accounts/verify/persistent/prod/resources.tf, terraform/accounts/verify/persistent/prod/variables.tf
Leaving the hsm module commented out for now as we don't need it yet in
production.
=> Fixing production persistence for Verify clusters.

pipelines/tools-staging-prod-infra.yaml
=> Add missing environment variables to addons tasks for Verify clusters.

terraform/accounts/verify/bootstrapper/main.tf, terraform/accounts/verify/clusters/prod/cluster.tf, terraform/accounts/verify/clusters/staging/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf, terraform/accounts/verify/persistent/prod/resources.tf, terraform/accounts/verify/persistent/staging/resources.tf, terraform/accounts/verify/persistent/tools/resources.tf, terraform/modules/hsm/main.tf
These changes have not yet been tested so should be verified before merging.
Solo: @poveyd
=> Pin version of alphagov/gsp-terraform-ignition repo

terraform/accounts/verify/bootstrapper/main.tf, terraform/accounts/verify/clusters/prod/cluster.tf, terraform/accounts/verify/clusters/staging/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf, terraform/accounts/verify/persistent/prod/resources.tf, terraform/accounts/verify/persistent/staging/resources.tf, terraform/accounts/verify/persistent/tools/resources.tf, terraform/modules/hsm/main.tf
```
find . -name \*.tf  -not -path '*/\.*' -exec gsed -i 's/fbc2c7896bd1f519eaea73ca1ac90be02a13e349/b2b356ddfc4b058aec4a20a7f2404987078e4be1/g' {} \;
```
=> Bump the ignition

pipelines/README.md, pipelines/tools-staging-prod-infra.yaml
Please note that this work has _not_ yet been tested and is just work-in-progress at the moment
=> Add gpg keys

terraform/accounts/verify/bootstrapper/main.tf, terraform/accounts/verify/clusters/prod/cluster.tf, terraform/accounts/verify/clusters/staging/cluster.tf, terraform/accounts/verify/clusters/tools/cluster.tf, terraform/accounts/verify/persistent/prod/resources.tf, terraform/accounts/verify/persistent/staging/resources.tf, terraform/accounts/verify/persistent/tools/resources.tf, terraform/modules/hsm/main.tf
=> bump terraform modules for helm-global-vars change

terraform/accounts/verify/clusters/tools/cluster.tf
We're now promoting the pipelines the same way as we're promoting
deployments.
We'd like to be monitoring the appropriate branch for changes.
- Sanity check
=> Use promoted pipeline

README.md
we now have per-user roles but haven't documented it anywhere, this is a
start
=> add some details about users/aws profiles

users/chris.farmiloe.yaml
escalate me to sandbox-admin so I can setup the HSM
=> escalate chris.farmiloe to sandbox-admin

users/daniel.blair.yaml
Reverts alphagov/gsp-teams#134
=> Revert "Make Daniel an admin in Verify to facilitate HSM initialisation."

namespaces/verify-proxy-node-integration/namespace.yaml, namespaces/verify-proxy-node-prod/namespace.yaml, users/christopher.wynne.yaml, users/john.watts.yaml, users/karol.gancarz.yaml, users/phillip.miller.yaml, users/tom.rosier.yaml
Get integration + prod namespaces and access configured for proxy-node
=> Create empty proxy-node namespaces

users/phillip.miller.yaml
=> phil's name was wrong

namespaces/gsp-canary/namespace.yaml
=> fix: canary dir was renamed

namespaces/sandbox-metadata-controller/vmc-secret.yaml
=> Add missing `---`

namespaces/sandbox-proxy-node-integration/vsp-secret.yaml
=> Fix YAML (again)

clusters/istiomesh-values.yaml, clusters/istiomesh.yaml
Add a sandbox cluster for testing the istio traffic management work.
=> Add a sandbox cluster for testing istio traffic management work

clusters/sandbox-values.yaml
=> Add new connector metadata namespace, change branch for metadata controller

clusters/sandbox-values.yaml
it's really hard to deploy stuff to sandbox from a branch
=> deploy verify-metadata-controller from master again

clusters/sandbox.yaml
See https://github.com/alphagov/gsp/pull/303
=> Add new key for approval count

clusters/sandbox.yaml
The other half of https://github.com/alphagov/gsp/pull/342.
=> Enable NLB in sandbox cluster

clusters/sandbox.yaml
=> Use the string "1" to mean `true`

clusters/sandbox-values.yaml
So devs can test changes without pushing to master
=> Add Proxy Node dev namespace

clusters/sandbox.yaml
We're running out of space on the sandbox account. Adding a node to each
AZ should last us for a long time now...
* Sanity check
=> Increase number of workers

README.md
Revert PRs are created by github, not one of us.
=> Noop for getting the build through.

clusters/sandbox-values.yaml, config/sandbox/sandbox-main/ingress-certificate.yaml
=> Enrol sandbox-main & canary into per-namespace ingress gateway.

clusters/sandbox-values.yaml
=> add talksToHsm label

clusters/sandbox-values.yaml
To replace https://github.com/alphagov/gsp/pull/468
=> Add permissions to access VMC resources

clusters/sandbox.yaml
See alphagov/gsp#584 for what this does.
=> Add extra workers per AZ

clusters/sandbox-values.yaml
I'd like a namespace with istio enabled to test some istio things out
in.
=> add a personal playground

clusters/sandbox.yaml
For https://github.com/alphagov/gsp/pull/610
=> Add new worker count keys to sandbox config

clusters/sandbox.yaml
https://github.com/alphagov/gsp/pull/635
=> Remove old worker-count key

clusters/sandbox-values.yaml
Should be replaced by https://github.com/alphagov/gsp/pull/566
=> Remove cluster-wide RDS egress rule

clusters/sandbox.yaml
This reverts commit 712908017e5f85085ca489826f184c19a72da788.
=> Re-enable CLS integration in sandbox

cluster-resources/verify_v1beta1_certificaterequest.yaml, cluster-resources/verify_v1beta1_metadata.yaml
Requires:
Should be merged / released with:
=> Add Metadata Controller CRDs to sandbox clusters.

clusters/sandbox.yaml
Using the variable we created in alphagov/gsp#609
=> Run sandbox workers as spot instances

clusters/sandbox-values.yaml
This has additional IP restrictions
=> Re-enable the sandbox CloudHSM
