alphagov/tech-ops-cluster-config

scripts/render.sh
terraform/modules/codecommit-kube-applier/data/kube-applier.yaml
terraform/modules/codecommit-kube-applier/main.tf
terraform/modules/codecommit-kube-applier/variables.tf
terraform/modules/gsp-cluster/main.tf
terraform/templates/cluster.tf

The "gsp-base" chart is now rendered and commited to a CodeCommit repo,
created as part of the terraform module. kube-applier is polling the repo
and applying the state accordingly.
Still to do: automate the "kubectly apply" for the kube-applier.

Use kube-applier with CodeCommit to create cluster resources.

---

terraform/clusters/cluster.re-managed-observe-staging.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/cluster.re-managed-observe-staging.aws.ext.govsvc.uk/kube-applier/gsp-base.yaml
terraform/templates/cluster.tf

Initial kubernetes cluster for Observe's staging is up and running.
Also fixed the template to stop duplication of terms in the generated names.
Pair: @blairboy362 @samcrang

Add initial cluster for Observe staging.

---

README.md

Some of the directories had previously been renamed so this updates those.
Also, some of the ordering of the instructions didn't make sense so the
order has been adjusted slightly to better reflect reality.
The `kubeconfig` is too large to fit in a `SecureString` so a re-think is needed here.

Some minor updates to the README.

---

terraform/modules/gsp-cluster/data/values.yaml

There is a 64 byte limit for a Common Name (CN). This means that a
certificate will fail to be issued for a cluster that has a cluster
that, for example, looks like the following:
```
concourse.cluster.re-managed-observe-production.aws.ext.govsvc.uk
```
We can work around this by setting the first thing in the list of hosts
to be a host that is more likely to be under this 64 byte limit. Other
hosts will be in the certificate's SubjectAltName (SAN) field which
don't have this length limit.

Workaround the 64 byte limit for Common Names

---

README.md
terraform/modules/gsp-cluster/main.tf
terraform/templates/cluster.tf

Send the necessary variables through to terraform-render-bootkube (via
typhoon) to correctly configure IAM authentication in the cluster. It also
creates a user-config kubeconfig file that is configured to connect to it.

Add IAM authentication for kubectl.

---

scripts/create_cluster_config.sh
terraform/clusters/rafalp.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/modules/gsp-cluster/data/values.yaml
terraform/modules/gsp-cluster/main.tf
terraform/templates/secrets.tfvars

We'd like to restrict the access to concourse by default. In order to
achieve that, we need to get rid of the defaults provided by our base
chart.
This will leave our tenants with ability to `kubectl proxy` || `kubectl
port-forwarding` which is a desirable way for safety keeping.
- Run `terraform apply`
- Run `kubectl apply -f kube-applier/gsp-base.yaml`
- Wait for the changes to be applied (Concourse to run)
- Follow the instructions in alphagov/gsp-team-manual#11
Make sure the `TMP` commit is pointing to the master branch of `gsp-base` - after merging alphagov/gsp-base#4.

Concourse auth

---

scripts/initialise_canary_helm_codecommit.sh

To avoid alerts during startup where the timestamp in the image is a long
time ago in a galaxy far far away we should update it during the creation
of the codecommit repo.

Update the timestamp before flux deploys the first one.

---

scripts/initialise_canary_helm_codecommit.sh
terraform/modules/canary/main.tf
terraform/modules/github-flux/data/helm-release.yaml
terraform/modules/github-flux/main.tf
terraform/modules/github-flux/variables.tf
terraform/templates/cluster.tf

Update the canary terraform module to include the necessary settings for
the canary updater container. Includes some modifications to the
github-flux module regarding the values. Yaml as strings again.
Updated the cluster template to include the monitoring chart in new
clusters.

Use the canary updater.

---

terraform/clusters/cluster.re-managed-observe-production.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/cluster.re-managed-observe-staging.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/danielblair.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/davidpye.re-run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/dougneal.gds-re-run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/farms.re-run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/modules/canary/main.tf
terraform/modules/github-flux/data/helm-release.yaml
terraform/modules/github-flux/data/values-secret.yaml
terraform/modules/github-flux/main.tf
terraform/modules/github-flux/variables.tf

Updates alertmanager releases in observe-* clusters to make use of a helm values defined in a Secret
The "farms" cluster is configured to point to the use-gsp-monitoring-operator branch as per https://github.com/alphagov/gsp-observe-alertmanager-spike/pull/3 so you can uyse that to test

Add alertmanager-secret-values reference to alertmanager releases

---

README.md

CLUSTER variable should actually be CLUSTER_NAME
Co-authored-by: David Pye <david.pye@digital.cabinet-office.gov.uk>
Co-authored-by: Paul Dougan <paul.dougan@digital.cabinet-office.gov.uk>

Fix Variable Name Typo

---

pipelines/tools-staging-prod-infra.yaml

fix: left the pipeline pointing at the wrong branch by mistake

watch master not provision-verify branch

---

terraform/accounts/verify/clusters/staging/cluster.tf

Now that we have defined what the deployment looks like, we can add it
to the list of things automatically taken care of by the internal GSP
system.

Add eIDAS deployment chart

---

pipelines/tools-staging-prod-infra.yaml
terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf
terraform/clusters/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/davidpye.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/pauld.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/samcrang.run-sandbox.aws.ext.govsvc.uk/cluster.tf

https://trello.com/c/qboQ4xcn/223-ship-logs-from-cloudwatch-into-splunk
- turns off splunk for dev stacks
- turns off splunk for prod EIDAS and tools EIDAS clusters as asked by cyber sec. The plan would be to turn these on for prod go live and turn staging off.
Requires https://github.com/alphagov/gsp-terraform-ignition/pull/26/files to be merged first

Add splunk to verify EIDAS staging cluster

---

pipelines/tools-staging-prod-infra.yaml

This image includes the `zip` package needed for terraform
See https://github.com/alphagov/gsp-docker-images/pull/8/files for more details. Note that PR will need merging and the docker image released before this PR can be merged

Use 0.13.0-beta.1 of terraform resource

---

pipelines/tools-staging-prod-infra.yaml
terraform/accounts/verify/clusters/staging/cluster.tf

We had to add these to all tasks (tools and production too) rather
than just staging as there is currently no way to do this per
cluster. This shouldn't actually do anything to tools and production,
just fix staging so that it has the variables it needs.
Has already been deployed and fixed this bug.

Add splunk terraform vars to addons tasks

---

terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

https://trello.com/c/nZqPwMsF/112-create-a-pipeline-for-promoting-deployment-charts-between-environments
As part of promotion, staging cluster should deploy from staging
branch of verify-edias-deployment.
We will want to do the same for production cluster to watch
production ranch of verify-eidas-deployment. We will do this when we
are ready to go live.
We output the github deployment public key from terraform which
is to be manually copied and added to the verify-eidas-deployment
with read and write access.

Staging EIDAS cluster to watch staging of verify-eidas-deployment

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

Sadly, the KIAM changes have somewhat broken down the Verify cluster.
For instance, the tool box is completely not accessible.
This is most likely with a side change enforcing the Canary to be always
enabled.
The clusters need to be running for the ongoing pen-tests and are not
required to have a canary just yet.
This should be then taken onto it's own story to establish the best ways
to proceed.
- See if the hash is one before KIAM changes
- We may be here for a while guessing...

Revert to a state without KIAM

---

terraform/accounts/verify/bootstrapper/main.tf

After recent refactoring of the ignition, we're now having to cleanup
some of the unused variables in order not to cause terraform failure.

Remove unused variable

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/modules/hsm/main.tf

Relies on https://github.com/alphagov/gsp-terraform-ignition/pull/35
- I only attempt to spin up a single HSM in the terraform code.
I could have set the count of the resource to be the number of
private subnets and the terraform would have likely failed the first
time, required the manual activation of the first HSM and then may
pass on a second run. However I discounted this option as I saw
strange behaviour in Terraform where it would create two HSMs but
would error on the third. I don't know if these two HSMs were
clones of each other or not. I was under the impression that you
should only be able to create a single HSM until you had activated
it so I wanted to avoid this confusing behaviour. Instead we
can either put in a PR later to bump the count of HSMs or scale
them manually …

Add AWS HSM to EIDAS staging and production clusters

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf
terraform/clusters/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/davidpye.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/pauld.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/samcrang.run-sandbox.aws.ext.govsvc.uk/cluster.tf

In the context of concourse, or when deferring the assume-role to
terraform as opposed to doing it outside like through aws-vault, the init
codecommit script doesn't inherit the assumed role environment so it would
fail to connect to codecommit with a 403. Pass the role arn down to the
updated gsp-cluster module so it can explicitly assume the right role.

Fix codecommit access permissions for verify terraform pipeline

---

pipelines/tools-staging-prod-infra.yaml

The new version of the resource should include `jq` needed by our
scripts to assume aws role.
- Code review
- (although image already pushed) Should be merged after alphagov/gsp-docker-images#9

Bump terraform-resource

---

terraform/accounts/verify/clusters/staging/cluster.tf

This value has been chosen by the cyber team and fits the
corresponding PR:
https://github.com/alphagov/gsp-terraform-ignition/pull/38/files
Note, the change of index requires a new hec token to be used which must be added to concourse before this can be deployed.

Add splunk index var

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

Due to some changes in the modules, we are no longer using the provider.
The existing terraform state however didn't have a chance to catch-up,
meaning it would fail to apply any changes.
Defining the empty provider and removing it after application has worked
in the past and we're following the known pattern.
- Code review should be sufficient

Define empty archive provider

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

the deployer concourse has two egress ips, we previously only
whitelisted one of them... this adds the second ip to allow deployer to
communicate with the provisioned cluster
* Code review
* watch the deployer pipelines after merge
* check that the addons jobs ran successfully

whitelist the autom8 egress for verify api-server

---

terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

This should give the dev team read-only access to the namespaces so they
can have a poke around the cluster and connect to the concourse dashboard.

Add eIDAS team members to dev roles in verify clusters.

---

terraform/accounts/verify/clusters/staging/cluster.tf
terraform/modules/hsm/main.tf

There is a default security group that is being created as part of the
HSM. Instead of creating a new one - which would likely tear down the
HSM cluster - we can create a new set of rules and attach them to that
magical existing group.
This is required for the workers to be able to interact with the HSM
Cluster.
There is no way of testing it really. You could spin up the cluster and HSM (along with initialising it), then re-run `terraform apply` from this branch to make sure HSM cluster is not being destroyed.

Attach rules to existing security group

---

terraform/accounts/verify/clusters/staging/cluster.tf
terraform/modules/hsm/main.tf

Revert recent change to allow ingress to hsm from workers with allowing ingress from anywhere inside the VPC private subnets.
Ideally we would only allow ingress from the "workers" security group to
lock it down a bit more, but this is not possible right now due to
ongoing work to split the hsm out into a seperate stage that is deployed
BEFORE the cluster exists.
Code review

Allow hsm access from within VPC subnets

---

terraform/modules/hsm/main.tf

the terraform docs hinted that the security_group_rules may overrwrite
any existing rules, so we duplicated the ones created by the hsm just in case.
This turned out to be incorrect and the dup records were causing errors.

remove self-ingress and self-egress hsm sg rules

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

Following an outage caused by a routine reboot, we are scaling out the
control plane for the verify clusters to make them more resilient.

Scale out verify cluster control plane.

---

terraform/accounts/verify/clusters/staging/cluster.tf
terraform/modules/hsm/main.tf

Applying this may take at least two runs if applying from scratch. The
Lambda log forwarder requires that the CloudWatch log group for the HSM
exists. Given this is created by the CloudHSM it's likely Terraform will
experience a race condition as this log group won't have been created.
To avoid this we could create the log group with the HSM module, and
`terraform import` the currently deployed state. We're going to not
bother doing this for the time being because the HSM creation is so
infrequent.

Send CloudHSM logs to Cyber's Splunk

---

terraform/accounts/verify/clusters/prod/cluster.tf

the hsm is quite expensive and there is no need for it right now, we can
spin it back up when it's time to initialize it

remove prod hsm (for now)

---

terraform/accounts/verify/clusters/staging/cluster.tf

Typo in splunk index is suspected issued for hsm log shipping failure
check you are happy with the transposed bytes

fix typo in splunk-index

---

README.md
pipelines/tools-staging-prod-infra.yaml
terraform/accounts/run-sandbox/persistent/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/main.tf
terraform/accounts/run-sandbox/persistent/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/outputs.tf
terraform/accounts/run-sandbox/persistent/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/resources.tf
terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf
terraform/accounts/verify/persistent/prod/main.tf
terraform/accounts/verify/persistent/prod/outputs.tf
terraform/accounts/verify/persistent/prod/resources.tf
terraform/accounts/verify/persistent/staging/main.tf
terraform/accounts/verify/persistent/staging/outputs.tf
terraform/accounts/verify/persistent/staging/resources.tf
terraform/accounts/verify/persistent/tools/main.tf
terraform/accounts/verify/persistent/tools/outputs.tf
terraform/accounts/verify/persistent/tools/resources.tf
terraform/clusters/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/cluster.tf
terraform/clusters/davidmcdonald.run-sandbox.aws.ext.govsvc.uk/outputs.tf

https://trello.com/c/wtEKyniL/283-separation-of-terraform-for-permanent-account-features-ie-hsms
Moves sealed secrets, HSM and VPC out of the cluster terraform project and into a persistent terraform project.
Note, in order for this to be deployed:
- We need to first initialise terraform remote states for the staging persistent project and then use `terraform mv` to move our HSM and VPC from the cluster project into the persistent project state
- https://github.com/alphagov/gsp-terraform-ignition/pull/49 needs to be merged
Paired: @poveyd and @idavidmcdonald

Terraform persistent components separately

---

pipelines/tools-staging-prod-infra.yaml
terraform/accounts/verify/persistent/staging/resources.tf
terraform/accounts/verify/persistent/staging/variables.tf

Some variables were missed when migrating the hsm and other state out of
the cluster and into a dedicated persistent terraform statefile. This
updates the pipeline to pass the variables through to the hsm module.

Add missing variables for terraforming hsm module in persistent state.

---

terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf

Terraform silently swallows the HTTP 404 that gets returned for an
incorrectly configured state bucket, allowing the apply to continue. Only
for it to fail later with missing required parameter values.
The pipeline sets config on the terraform tasks which adds a workspace to
the remote state. This results in the clusters not using the correct url
to load the remote state. Setting the workspace should fix it, as per
the bootstrapper terraform.

Fix persistent remote state configuration.

---

pipelines/tools-staging-prod-infra.yaml
terraform/accounts/verify/clusters/tools/cluster.tf

We'd like to automatically read in our `users/` directory and obtain the
public key for people who are allowed to sign the commits when
contributing to app repositories.
It needs to be managed through terraform that will compose a new file in
`addons/` directory and then apply it to the cluster.
These keys then will be loaded by our tenant's concourse and embedded
into their pipelines where needed to avoid unsigned commits being rolled
into production environment or being built.
- Sanity check
- Either run our pipelines locally... or trust it will work and/or fix later...

Pass on the public keys to the verify pipelines

---

pipelines/tools-staging-prod-infra.yaml
terraform/accounts/verify/bootstrapper/main.tf
terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf
terraform/accounts/verify/persistent/prod/resources.tf
terraform/accounts/verify/persistent/staging/resources.tf
terraform/accounts/verify/persistent/tools/resources.tf
terraform/modules/hsm/main.tf

We [forked flux](https://github.com/alphagov/gsp-flux/tree/gds-master) to implement commit signing.... and [updated the flux-release modules](https://github.com/alphagov/gsp-terraform-ignition/pull/59) to accept commit verification.
This PR updates the pipelines to pass through the GPG private/public keys to the ci-system-main team and flux-releases that require them.
* ~~There is a TMP commit to point to the commit in https://github.com/alphagov/gsp-terraform-ignition/pull/59 ... please ensure that PR is merged and the TMP commit references the correct SHA before merging~~

Commit verification for flux-releases

---

terraform/accounts/run-sandbox/persistent/samcrang.run-sandbox.aws.ext.govsvc.uk/outputs.tf
terraform/accounts/verify/persistent/prod/outputs.tf
terraform/accounts/verify/persistent/staging/outputs.tf
terraform/accounts/verify/persistent/tools/outputs.tf

prevent terraform plan/apply from exposing the sealed secrets private
key during pipeline runs

mark sealed secrets key as sensitive output

---

terraform/accounts/verify/clusters/tools/cluster.tf

We've moved this piece out of gsp-cluster module into flux-release. It
being here will cause the terraform to fail and stop the pipeline.

Remove the deprecated output

---

terraform/accounts/verify/persistent/staging/resources.tf

enable the lambda that forwards hsm log group to splunk

enable the hsm log forwarding lambda

---

terraform/accounts/verify/clusters/staging/cluster.tf

the test-proxy-node deployment should have the stubConnector enabled

set stubConnector.enabled=true for test-proxy-node

---

pipelines/README.md

--var causes a big stringified blob when applying pipeline, it should be
--yaml-var

Use --yaml-var not --var when set-pipeline

---

pipelines/tools-staging-prod-infra.yaml

Rejig the pipeline so the bootstrapper jobs have to be ran manually and move them to own group.
Pipeline has already been applied with `fly`.

move bootstrapper jobs to own group

---

terraform/accounts/verify/bootstrapper/main.tf
terraform/accounts/verify/clusters/prod/cluster.tf
terraform/accounts/verify/clusters/staging/cluster.tf
terraform/accounts/verify/clusters/tools/cluster.tf
terraform/accounts/verify/persistent/prod/resources.tf
terraform/accounts/verify/persistent/staging/resources.tf
terraform/accounts/verify/persistent/tools/resources.tf
terraform/modules/hsm/main.tf

the account_name is used to set alerting labels in monitoring-system so
we want to set it to "verify" so that alerts are correctly routed

set account_name for Verify clusters

---

pipelines/README.md
pipelines/deployer.yaml
pipelines/terraform/cluster/main.tf
pipelines/terraform/cluster/variables.tf

Expose variables in the pipeline to specify the version of EKS to deploy
and pass those down to the gsp-cluster module.

Specify the EKS version.

---

pipelines/tools-staging-prod-infra.yaml

we are not using the "prod" cluster and so to save money we run destory
on it... but it comes back to life when the pipeline runs... this
removes it from the pipeline

remove "prod" from Verfy pipeline

---

hack/set-pipeline.sh

set-pipeline script was noisy and gave false positive when clean... silences output to dev/null and inverts the check

silence set-pipeline dirty checking

---

users/daniel.blair.yaml

This will be rolled back once the HSM has been initialised.

Make Daniel an admin in Verify to facilitate HSM initialisation.

---

clusters/sandbox.yaml
clusters/verify.yaml

the pipeline is now parameterised for configuring instance types, this
sets the types for sandbox and verify clusters
sandbox is using smaller ci-nodes as we do not currently expect to need
them much.

add instance types to cluster configs

---

clusters/sandbox.yaml

t3.micro is only capable of running 4x pods due to the ENI limit.
4 pods will be running on each node as a minimum as there are daemonsets
for things like VPC CNI, istio, log shipping, ssm so there is no room
left for anything else.
t3.small is capable of running 12 pods (3x ENI with 4x IPs each) so is a
more reasonable choice.

t3.micro is too small for ci worker

---

clusters/portfolio.yaml
users/anshul.sirur.yaml
users/chris.farmiloe.yaml
users/daniel.blair.yaml
users/rafal.proszowski.yaml
users/sam.crang.yaml

The team responsible for Portfolio, may also be onboarding teams onto
GSP. Adding the configuration pre-emptively to initiate this process.
There are no splunk configuration details at current time.
- Sanity check
... Do not deploy/~push pipeline~ ... 🤔

Add portfolio cluster configuration

---

namespaces/verify-proxy-node-staging-test/build-pipeline.yaml
namespaces/verify-proxy-node-staging-test/deploy-pipeline.yaml

The tests seem to fail quite often due to seemingly random timeouts. This is an attempt to improve the reliability of our builds.
As suggested in https://github.com/alphagov/verify-eidas-pipelines/pull/42#issuecomment-492150739
Also change verify-service-provider-config-repo icon to settings

BAU: Re-run failed tests

---

namespaces/verify-proxy-node-integration/deploy-pipeline.yaml

we'd like to ensure that the application gets deployed and rolled at least once a
day from the latest release so we can reason about the max lifetime of
the application pods.
* we add a unique "deployed-at" label so that there is always something unique to update on pods
* we add a timer to the deploy that triggers once a day between 8AM and 8PM (so that on the off-chance that the timer initiated deploy causes an issue, it will at least occur during waking hours)
... we intend to copy this pattern for prod deployments

Deploy proxy-node to integration at least once a day

---

clusters/portfolio.yaml
clusters/sandbox.yaml
clusters/verify.yaml

The `github` resource requires a PR with a minimum number of approvals.
This makes changes to the sandbox cluster (and possibly other places
where we need to iterate quickly) awkward.
This change replaces the `github` resource with the `git` resource in
the sandbox cluster.

Allow sandbox cluster to have less restrictive deployments

---

namespaces/sandbox-proxy-node-integration/deploy-pipeline.yaml

A given label is immutable once a pod has been scheduled so a
time-sensitive value isn't appropriate.

Workaround for broken deployment.

---

clusters/sandbox.yaml

It didn't do anything..
Reverts alphagov/gsp-teams#186

Revert "Remove approval keys in an attempt to workaround approval requirements."

---

namespaces/verify-proxy-node-integration/deploy-pipeline.yaml

A given label is immutable once a pod has been scheduled so a time-sensitive value isn't appropriate.
The same workaround [has been applied to the sandbox namespace](https://github.com/alphagov/gsp-teams/pull/185) but the old namespace is still being used.

Workaround for broken NL deployment

---

namespaces/verify-proxy-node-build/release-pipeline.yaml

The pipeline needs to release in order to fix tests..

Temporarily allow a test release blocked by tests job

---

namespaces/verify-proxy-node-build/release-pipeline.yaml

We deleted tests before release in <https://github.com/alphagov/gsp-teams/pull/192>.
This restores `test` to its correct position in pipeline

Restore test before release to build pipeline

---

namespaces/verify-metadata-controller/release-pipeline.yaml

cloudhsm is a container run by the vmc pod. We need to make sure we pull
it from a "proper" registry and not the default one that no longer
exists.

Use CloudHSM image from the correct registry

---

clusters/portfolio.yaml

We need an example namespace to allow generate_namespace_values to pass within the deployment.
Solo: @smford

Adding an example namespace to portfolio

---

clusters/sandbox-values.yaml

This exposes the sandbox cloudhsm for use by EIDAS in their local development environment.
Solo: @smford

Expose CloudHSM in Sandbox Environment to GDS IP Range

---

clusters/sandbox.yaml

the gsp deployer pipeline now reads from releases, this removes the
redudent config vars and sets the platform-pre-release arg which allows
following pre-releases as well as propper releases (allowing sandbox to
get previews of releases)

allow deploying sandbox from pre-releases

---

clusters/sandbox-values.yaml

Remove the old AWS one and its namespace role stuff
(going away in https://github.com/alphagov/gsp/pull/412),
add a new one for GSP.

Change service operator test namespaces

---

clusters/sandbox-values.yaml

awscli uses this because boto3 does.

Safelist SQS legacy endpoint too

---

clusters/sandbox-values.yaml

- We're using our self-built GSP Service Operator to allow tenants to make use of Amazon RDS instances (Aurora Postgres). Without this change, things in the cluster can't actually access things on rds.amazonaws.com and create, read, update or delete their databases.
- This is in the new syntax based on the edited Helm chart in the GSP repo, because RDS uses different ports to HTTPS and so we're setting values for all of the hosts and ports items now.
- Also we convert the existing ServiceEntry values to the new format so that they apply (this is tested with `hack/lint-teraform-values-output.sh` in the GSP repo. This is more verbose, but users don't have to go digging into the Helm chart templates in the GSP repo to find what values they need to pass, or values that are already there by …

Allow clusters access to RDS via `egressSafelist` specifying host and port

---

clusters/sandbox-values.yaml

it's not possible to use a host with a TCP proto ServiceEntry without a
network endpoint.
postgres is over a TLS connection so it should be TLS.

changes rds ServiceEntry to TLS proto

---

clusters/sandbox-values.yaml

egressSafelist requires a the ServiceEntry spec under a "service" key

adds missing "service" key

---

clusters/sandbox-values.yaml

it's not possible to use a wildcard host with DNS resolution.
using resolution:NONE means that the destination IP is trusted and the
istio sidecar will not attempt to lookup the IP itself.
using resolution:NONE alone would introduce the possibility to
exfiltrate data by spoofing SNI, so we scope the addresses to only
thoses within the VPC.

use resolution:NONE for postgres ServiceEntry

---

clusters/sandbox-values.yaml

- The Postgres default port of 5432 is not correct. Aurora exposes 3306
for Postgres, which is confusingly also the MySQL port.

Specify the correct port number for RDS Aurora Postgres

---

clusters/sandbox-values.yaml

- We were seeing issues connecting to AWS RDS from Istio-managed
namespaces such that the connection would never get to Amazon, it
would be blocked by Istio, like:
```
psql: server closed the connection unexpectedly
This probably means the server terminated abnormally
before or while processing the request.
```
- This change sets `protocol` to `TCP` instead of `TLS` so that we allow
all traffic on port 3306 to the entire VPC subnet. Maybe we should
clean this up in a later commit? But for now, it unblocks DCS.
Co-authored-by: Issy Long <isabell.long@digital.cabinet-office.gov.uk>
Co-authored-by: Daniel Blair <daniel.blair@digital.cabinet-office.gov.uk>

Fix RDS access from Istio-managed namespaces

---

clusters/sandbox-values.yaml

- This gave an error:
```
Error from server: error when creating
"manifests/gsp-cluster/templates/02-gsp-system/egress-safelist.yaml":
admission webhook "pilot.validation.istio.io" denied the request:
configuration is invalid: hosts must be FQDN if no endpoints are
provided for resolution mode DNS
```

Fix Istio resolving the wildcard s3 domain

---

clusters/sandbox-values.yaml

we hardcode the s3 endpoint ips because the alternative would be to
create a ServiceEntry in cluster-config for every bucket provisioned by
the service operator which would be a pain.
addrs pulled from:
`curl https://ip-ranges.amazonaws.com/ip-ranges.json | jq -r '.prefixes[] | select(.region=="eu-west-2") | select(.service=="S3") | .ip_prefix'`

hardcoded s3 endpoint service-entry

---

clusters/sandbox.yaml

This scales down our original worker ASG to 0 nodes.
The `extra-workers-per-az-count` value guarantees that we will still
have at least 1 worker per AZ.
alphagov/gsp#600 added the cluster autoscaler, which I'm hoping will
scale up the per-AZ nodegroups to compensate for the loss of these
nodes.  Furthermore, it will scale the cluster to the right size for
the number & size of pods it's running.

Scale down original worker ASG to 0

---

clusters/sandbox-values.yaml

To test the new Service Operator dynamic creation of ServiceEntries.

Remove cluster-global S3 ServiceEntry

---

clusters/sandbox.yaml

We're hitting the limit now so stuff is not getting scheduled and the sandbox
is broken.

Allow sandbox to scale up to 4 worker nodes per AZ

---

clusters/sandbox-values.yaml

This isn't needed and it's causing alert noise
This will require manual cleanup afterwards

remove namespace sandbox-phil-playground

---

clusters/sandbox.yaml

We weren't taking advantage of the difference.

Swap from m5d.large worker nodes to m5.large

---

clusters/sandbox.yaml

This won't have any effect until https://github.com/alphagov/gsp/pull/798 is done. `cls-destination-arn` will be injected via a Big Concourse secret.

Enable CLS integration in sandbox

---

clusters/sandbox.yaml

This reverts commit f831fbef0de6c6bfd4d27b77d90973d01494b2bc.
We haven't been whitelisted for access and won't be today.

Revert "Enable CLS integration in sandbox"

---

clusters/sandbox.yaml

This reverts commit 5739ca7065f4cb4c207d4e8a5462f3fecf3e9e83.
Let's re-run this with https://github.com/alphagov/gsp/pull/799 and https://github.com/alphagov/gsp/pull/803

Revert "Swap from m5d.large worker nodes to m5.large"

---

clusters/sandbox.yaml

This reverts commit fac5be29d239606550587b43d8c3359dfd4848b5.
Access was revoked as things stopped working when we started sending logs.

Revert "Re-enable CLS integration in sandbox"

---

clusters/sandbox-values.yaml

Add egress URLs for the multi-country proxy node so that metadata can be retrieved.

Add multi-country proxy node egress urls

---

cluster-resources/verify_vmc_clusterrole.yaml
cluster-resources/verify_vmc_clusterrolebinding.yaml

Since https://github.com/alphagov/gsp/pull/855, VMC can't deploy these itself.

Copy in VMC ClusterRole things from verify-metadata-controller

---

clusters/sandbox.yaml

production clusters use xlarge worker nodes, this changes sandbox to
also use xlarge nodes, keeping the sandbox workers more inline with
production clusters when it comes to memory limits.
since CPU ultilization is below 50% accross all the nodes in sandbox, it
makes sense for these to be t3 instances to save money.

use t3.xlarge for sandbox workers

---

clusters/sandbox.yaml

This doesn't do anything any more since the spot instances work

remove worker-instance-type variable

---

clusters/sandbox.yaml

Use the new worker-on-demand-base-capacity config value to run 0 base
capacity on-demand instances and 0% on-demand instances above that.

Run 100% spot instances
